services:
  cassandra-node1:
    image: cassandra:latest
    container_name: cassandra-node1
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCluster
      - CASSANDRA_NUM_TOKENS=256
      - CASSANDRA_SEEDS=cassandra-node1
    volumes:
      - cassandra_node1_data:/var/lib/cassandra
    ports:
      - "7000:7000"
      - "7001:7001"
      - "7199:7199"
      - "9042:9042"
      - "9160:9160"
    networks:
      - cassandra-net
    deploy:
      resources:
        limits:
          memory: 2g

volumes:
  cassandra_node1_data:

networks:
  cassandra-net:
